### ISSUE TITLE
pip install Python 3.12

### ISSUE THREAD

**Issue by bk1n** [pnxenopoulos/awpy#297]
**Describe the bug**
Attempting to install awpy via pip with Python version 3.12

**Include Information to Reproduce**
`pip install awpy`

**Screenshots**
```
$ pip install awpy
Collecting awpy
  Using cached awpy-1.3.1.tar.gz (55.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting imageio~=2.28.0 (from awpy)
  Using cached imageio-2.28.1-py3-none-any.whl (3.4 MB)
Collecting matplotlib~=3.7.0 (from awpy)
  Obtaining dependency information for matplotlib~=3.7.0 from https://files.pythonhosted.org/packages/e6/2d/8b91c3727c28e9e2ca345aaf1e06783f17c0fc40b2bf32273195ceaec127/matplotlib-3.7.3-cp312-cp312-win_amd64.whl.metadata
  Using cached matplotlib-3.7.3-cp312-cp312-win_amd64.whl.metadata (5.8 kB)
Collecting networkx~=3.1 (from awpy)
  Using cached networkx-3.1-py3-none-any.whl (2.1 MB)
Collecting numpy<=1.25,>=1.20 (from awpy)
  Using cached numpy-1.25.0.tar.gz (10.4 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [33 lines of output]
      Traceback (most recent call last):
        File "D:\<user>\miniconda3\envs\cdr\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\<user>\miniconda3\envs\cdr\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\<user>\miniconda3\envs\cdr\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 112, in get_requires_for_build_wheel
          backend = _build_backend()
                    ^^^^^^^^^^^^^^^^
        File "D:\<user>\miniconda3\envs\cdr\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 77, in _build_backend
          obj = import_module(mod_path)
                ^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\<user>\miniconda3\envs\cdr\Lib\importlib\__init__.py", line 90, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1304, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1381, in _gcd_import
        File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
        File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 994, in exec_module
        File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
        File "C:\Users\<user>\AppData\Local\Temp\pip-build-env-g1ij0qjp\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
          import setuptools.version
        File "C:\Users\<user>\AppData\Local\Temp\pip-build-env-g1ij0qjp\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
          import pkg_resources
        File "C:\Users\<user>\AppData\Local\Temp\pip-build-env-g1ij0qjp\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
          register_finder(pkgutil.ImpImporter, find_on_path)
                          ^^^^^^^^^^^^^^^^^^^
      AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```
```
pip freeze 
```
![image](https://github.com/pnxenopoulos/awpy/assets/75484578/04be2a7d-5f90-487b-ae9e-9b2acfab6a36)

**Additional context**
Could be due to numpy version installed with Python 3.12 in conda environment? See issue [here](https://github.com/pypa/pip/issues/12179)

**Comment by JanEricNitschke** [comment]
Working on python 3.12 compatibility here: https://github.com/pnxenopoulos/awpy/pull/296

But there is currently not a lot of manpower available.

Feel free to have a look at this and make a PR if you are interested and have the time.

**Comment by pnxenopoulos** [comment]
@bk1n Awpy v2 has changed a lot. There is 3.12 support now, but it's rather recent. Please feel free to reopen this issue or make new ones if you encounter any errors!
